In [1]:
import numpy as np

In [2]:
vector = [1, 2, 3]
type(vector)

list

In [3]:
nvector = np.array(vector)
type(nvector)

numpy.ndarray

In [4]:
nvector.shape

(3,)

In [5]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
type(matrix)

list

In [6]:
nmatrix = np.array(matrix)
type(nmatrix)

numpy.ndarray

In [7]:
nmatrix.shape

(3, 3)

In [8]:
narr = np.array([1, 2, 3])
narr

array([1, 2, 3])

In [9]:
np.resize(narr, [4, 4])

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [10]:
narr.resize([3, 3], refcheck=False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
matrix = np.ones([5, 4])
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
matrix = np.zeros([3, 3])
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
m1 = np.ones([5, 4], int)
m1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
m2 = np.zeros([5, 4], int)
m2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.vstack([m1, m2])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.hstack([m1, m2])

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [17]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [18]:
z = x*y
z

array([ 4, 10, 18])

In [19]:
x**2

array([1, 4, 9])

sum(x*y) = x.dot(y)

In [20]:
x.dot(y) 

np.int64(32)

In [21]:
narr = np.random.randint(0, 10, (4, 3)) 
narr

array([[0, 8, 4],
       [6, 5, 7],
       [4, 7, 9],
       [3, 0, 5]], dtype=int32)

In [22]:
narr.T

array([[0, 6, 4, 3],
       [8, 5, 7, 0],
       [4, 7, 9, 5]], dtype=int32)

In [23]:
np.argmax(narr)

np.int64(8)

In [24]:
np.argmin(narr)

np.int64(0)

In [25]:
np.mean(narr)

np.float64(4.833333333333333)

In [26]:
marr = np.arange(15)**2
marr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [27]:
narr[narr >= 5]

array([8, 6, 5, 7, 7, 9, 5], dtype=int32)

In [28]:
narr >= 5

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [29]:
parr = narr[-1]
parr

array([3, 0, 5], dtype=int32)

In [31]:
parr[:] = 1
parr

array([1, 1, 1], dtype=int32)

In [32]:
narr

array([[0, 8, 4],
       [6, 5, 7],
       [4, 7, 9],
       [1, 1, 1]], dtype=int32)

In [36]:
parr = narr.copy()
parr = parr[-2]
parr

array([4, 7, 9], dtype=int32)

In [37]:
parr[:] = 0
parr

array([0, 0, 0], dtype=int32)

In [38]:
narr

array([[0, 8, 4],
       [6, 5, 7],
       [4, 7, 9],
       [1, 1, 1]], dtype=int32)