In [94]:
import numpy as np

In [95]:
vector = [1, 2, 3]
type(vector)

list

In [96]:
nvector = np.array(vector)
type(nvector)

numpy.ndarray

In [97]:
nvector.shape

(3,)

In [98]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
type(matrix)

list

In [99]:
nmatrix = np.array(matrix)
type(nmatrix)

numpy.ndarray

In [100]:
nmatrix.shape

(3, 3)

In [101]:
narr = np.array([1, 2, 3])
narr

array([1, 2, 3])

In [102]:
np.resize(narr, [4, 4])

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [103]:
narr.resize([3, 3], refcheck=False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [104]:
matrix = np.ones([5, 4])
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [105]:
matrix = np.zeros([3, 3])
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [106]:
m1 = np.ones([5, 4], int)
m1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [107]:
m2 = np.zeros([5, 4], int)
m2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [108]:
np.vstack([m1, m2])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [109]:
np.hstack([m1, m2])

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [110]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [111]:
z = x*y
z

array([ 4, 10, 18])

In [112]:
x**2

array([1, 4, 9])

sum(x*y) = x.dot(y)

In [113]:
x.dot(y) 

np.int64(32)

In [114]:
narr = np.random.randint(0, 10, (4, 3)) 
narr

array([[8, 7, 5],
       [4, 8, 7],
       [9, 9, 8],
       [0, 7, 6]], dtype=int32)

In [115]:
narr.T

array([[8, 4, 9, 0],
       [7, 8, 9, 7],
       [5, 7, 8, 6]], dtype=int32)

In [116]:
np.argmax(narr)

np.int64(6)

In [117]:
np.argmin(narr)

np.int64(9)

In [118]:
np.mean(narr)

np.float64(6.5)

In [119]:
marr = np.arange(15)**2
marr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [120]:
narr[narr >= 5]

array([8, 7, 5, 8, 7, 9, 9, 8, 7, 6], dtype=int32)

In [121]:
narr >= 5

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [122]:
parr = narr[-1]
parr

array([0, 7, 6], dtype=int32)

In [123]:
parr[:] = 1
parr

array([1, 1, 1], dtype=int32)

In [124]:
narr

array([[8, 7, 5],
       [4, 8, 7],
       [9, 9, 8],
       [1, 1, 1]], dtype=int32)

In [125]:
parr = narr.copy()
parr = parr[-2]
parr

array([9, 9, 8], dtype=int32)

In [126]:
parr[:] = 0
parr

array([0, 0, 0], dtype=int32)

In [127]:
narr

array([[8, 7, 5],
       [4, 8, 7],
       [9, 9, 8],
       [1, 1, 1]], dtype=int32)

In [128]:
import time

In [129]:
time.time()

1754581730.4194531

In [130]:
def python_version():
    t1 = time.time()
    X = range(100000000)
    Y = range(100000000)
    Z = []
    for i in range(100000000):
        Z.append(X[i] + Y[i])
    t2 = time.time()
    return t2 - t1

In [131]:
python_version()

47.63504409790039

In [132]:
def numpy_version():
    t1 = time.time()
    X = np.arange(10000000)
    Y = np.arange(10000000)
    Z = X + Y
    
    t2 = time.time()
    return t2 - t1

In [133]:
numpy_version()

0.2739861011505127