In [18]:
import numpy as np

In [19]:
# create array , matrix

a = np.array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
b = np.array([[1, 2], [3, 4]])

In [22]:
b

array([[1, 2],
       [3, 4]])

In [23]:
# shape
print(a.shape, b.shape)

(4,) (2, 2)


In [24]:
# reshape
c = a.reshape((4, 1))
c

array([[1],
       [2],
       [3],
       [4]])

In [25]:
c.shape

(4, 1)

In [26]:
d = a.reshape((2, 2, 1))
d.shape

(2, 2, 1)

In [27]:
c = a.reshape((2 , -1, 1))
c.shape

(2, 2, 1)

In [28]:
# concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a ,b))
c

array([1, 2, 3, 4, 5])

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
c

array([5, 7, 9])

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
c

array([ 4, 10, 18])

In [31]:
c = np.array([10])

d = a + c
d

array([11, 12, 13])

In [32]:
e = a + 5
e

array([6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [35]:
b = a[2:7]
b

array([3, 4, 5, 6, 7])

In [36]:
b = a[2:7:2]
b

array([3, 5, 7])

In [37]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [38]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
sum_a = np.sum(a)
sum_a

np.int64(36)

In [40]:
max_a = np.max(a)
max_a

np.int64(8)

In [41]:
min_a = np.min(a)
min_a

np.int64(1)

In [42]:
a = np.array([4, 2, 9, 8, 5, 3, 1])
b = np.sort(a)
b

array([1, 2, 3, 4, 5, 8, 9])

In [45]:
a = np.random.randint(-100, 100, (3, 4))
print(a)

[[ 80 -97  41  40]
 [ 64 -57 -29 -95]
 [ 24 -13 -39  88]]


In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
c.shape

(2, 3)

In [48]:
c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6])

In [49]:
# normalize
mean_a = np.mean(a)
mean_a

np.float64(2.0)

In [50]:
std_a = np.std(a)
std_a

np.float64(0.816496580927726)

In [51]:
norm_a = (a - mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [52]:
np.mean(norm_a)

np.float64(0.0)

In [ ]:
np.std(norm_a)

np.float64(0.9999999999999999)